apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: snow-demo-dev-frontend

nameSuffix: -frontend

patches:
- target:
    kind: Ingress
    name: stable-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: snow-demo-dev-frontend.akpdemoapps.link
- target:
    kind: Rollout
    name: rollouts-app
  patch: |-
    - op: replace
      path: /spec/strategy/canary/canaryService
      value: rollouts-svc-canary-frontend
    - op: replace
      path: /spec/strategy/canary/stableService
      value: rollouts-svc-stable-frontend
    - op: replace
      path: /spec/strategy/canary/steps/2/analysis/templates/0/templateName
      value: loadgen-frontend
- target:
    kind: AnalysisTemplate
    name: loadgen
  patch: |-
    - op: replace
      path: /spec/metrics/0/provider/job/spec/template/spec/containers/0/command
      value: [ab, "-n20", "-mPOST", "http://snow-demo-dev-frontend.akpdemoapps.link/"]

