
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snow-credentials
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: snow-credentials
    template:
      engineVersion: v2
      data: 
        username: "{{.username}}"
        password: "{{.password}}"
  data:
  - secretKey: username
    remoteRef:
      key: sedemo/cluster-secrets
      property: snow-username
  - secretKey: password
    remoteRef:
      key: sedemo/cluster-secrets
      property: snow-password