apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: loadgen
        image: jordi/ab
        command: ["/bin/sh", "-c"]
        args:
        - "sleep 10 && ab -n2000 -mPOST http://{{  .Release.Namespace }}.{{ .Values.ingress.root_domain }}/color"
      restartPolicy: Never
  backoffLimit: 1