name: Publish new image
run-name: Publish new lamda

on:
  push:
    branches:
      - main
    paths:
      - 'beyond-k8s/lambda-app/**'
      - '.github/workflows/beyond-k8s-lamda.yml'
permissions:
  packages: write
  attestations: write
  contents: read
  id-token: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-beyond-k8s-lambda

jobs:
  publish:
    defaults:
      run:
        working-directory: beyond-k8s/lambda-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        id: push
        with:
          context: beyond-k8s/lambda-app
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:0.1.${{ github.run_number }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  cleanup:
    name: ghcr.io cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-tagged: 5
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-untagged: true
          packages: sedemo-monorepo-beyond-k8s-lambda
